#!/bin/bash
#
# TITLE: (System) Apply Kernel Hardening
# SKYNET_HIDDEN: true
#
# Применяет безопасные настройки sysctl на удаленном сервере.

# --- Standard helpers for Skynet plugins ---
set -e # Exit immediately if a command exits with a non-zero status.
C_RESET='\033[0m'; C_RED='\033[0;31m'; C_GREEN='\033[0;32m'; C_YELLOW='\033[1;33m';
info() { echo -e "${C_RESET}[i] $*${C_RESET}"; }
ok()   { echo -e "${C_GREEN}[✓] $*${C_RESET}"; }
warn() { echo -e "${C_YELLOW}[!] $*${C_RESET}"; }
err()  { echo -e "${C_RED}[✗] $*${C_RESET}"; exit 1; }
# --- End of helpers ---

info "Применяю настройки безопасности ядра (Kernel Hardening)..."

SYSCTL_CONF_FILE="/etc/sysctl.d/99-reshala-hardening.conf"

_resolve_iface_name() {
    local iface="$1"
    local resolved
    [[ -n "$iface" ]] || return 1

    resolved=$(ip -o link show "$iface" 2>/dev/null | awk -F': ' 'NR==1 {print $2}')
    resolved="${resolved%%@*}"
    [[ -n "$resolved" ]] || return 1
    echo "$resolved"
}

_interface_exists() {
    local iface="$1"
    local resolved
    [[ -n "$iface" ]] || return 1
    resolved=$(_resolve_iface_name "$iface") || return 1
    [[ -n "$resolved" ]]
}

_get_default_interface() {
    local iface
    local resolved_iface
    iface=$(ip -o route show default 2>/dev/null | awk '{print $5; exit}' | cut -d'@' -f1)
    [[ -z "$iface" ]] && return 0
    resolved_iface=$(_resolve_iface_name "$iface" 2>/dev/null || true)
    echo "${resolved_iface:-$iface}"
}

_get_first_active_public_interface() {
    local iface
    local resolved_iface
    iface=$(ip -o link show up 2>/dev/null \
        | awk -F': ' '$2 != "lo" && $2 != "wt0" {split($2, p, "@"); print p[1]; exit}')
    [[ -z "$iface" ]] && return 0
    resolved_iface=$(_resolve_iface_name "$iface" 2>/dev/null || true)
    echo "${resolved_iface:-$iface}"
}

_pick_public_interface() {
    if [[ -n "${RESHALA_PUBLIC_IFACE:-}" ]]; then
        if _interface_exists "$RESHALA_PUBLIC_IFACE"; then
            _resolve_iface_name "$RESHALA_PUBLIC_IFACE" 2>/dev/null || echo "$RESHALA_PUBLIC_IFACE"
            return 0
        fi
        warn "RESHALA_PUBLIC_IFACE=${RESHALA_PUBLIC_IFACE} не найден. Использую автоопределение."
    fi

    local iface
    iface=$(_get_default_interface)
    if [[ -n "$iface" && "$iface" != "lo" && "$iface" != "wt0" ]]; then
        echo "$iface"
        return 0
    fi

    iface=$(_get_first_active_public_interface)
    echo "$iface"
}

main_public_iface=""
rp_filter_comment="# rp_filter: strict (стандартный профиль для серверов без NetBird)"
rp_filter_all="1"
rp_filter_default="1"
rp_filter_main_line=""
rp_filter_wt0_line=""

if _interface_exists "wt0"; then
    main_public_iface=$(_pick_public_interface)
    if [[ -n "$main_public_iface" ]]; then
        rp_filter_comment="# rp_filter: loose/точечно, чтобы не ломать policy routing (NetBird fwmark)"
        rp_filter_all="0"
        rp_filter_default="0"
        rp_filter_main_line="net.ipv4.conf.${main_public_iface}.rp_filter = 1"
        rp_filter_wt0_line="net.ipv4.conf.wt0.rp_filter = 2"
        info "Обнаружен wt0. Применяю NetBird-совместимый профиль (основной интерфейс: ${main_public_iface})."
    else
        warn "wt0 обнаружен, но основной публичный интерфейс не найден. Использую strict-профиль."
    fi
else
    info "wt0 не обнаружен. Использую strict-профиль RP Filter."
fi

# Создаём конфиг
tee "$SYSCTL_CONF_FILE" > /dev/null << SYSCTL
# Generated by Reshala Security Module
#
# Kernel Hardening & Performance Tuning
#

# --- SYN Flood Protection ---
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_synack_retries = 2
net.ipv4.tcp_syn_retries = 2
net.ipv4.tcp_max_syn_backlog = 4096
net.core.somaxconn = 4096
net.core.netdev_max_backlog = 4096

# --- IP Spoofing & Network Attack Protection ---
net.ipv4.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
${rp_filter_comment}
net.ipv4.conf.all.rp_filter = ${rp_filter_all}
net.ipv4.conf.default.rp_filter = ${rp_filter_default}
${rp_filter_main_line}
${rp_filter_wt0_line}
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.all.secure_redirects = 0
net.ipv4.conf.default.secure_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0
net.ipv4.icmp_echo_ignore_broadcasts = 1
net.ipv4.icmp_ignore_bogus_error_responses = 1

# --- TCP Tuning ---
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 15
net.ipv4.tcp_keepalive_time = 600
net.ipv4.tcp_keepalive_probes = 5
net.ipv4.tcp_keepalive_intvl = 15

# --- Kernel Security ---
kernel.randomize_va_space = 2
kernel.dmesg_restrict = 1
kernel.yama.ptrace_scope = 1
fs.protected_symlinks = 1
fs.protected_hardlinks = 1

# IP Forwarding is intentionally left untouched for VPN compatibility
SYSCTL

ok "Конфигурационный файл создан: $SYSCTL_CONF_FILE"

info "Применяю настройки..."
if ! sysctl -p "$SYSCTL_CONF_FILE" >/dev/null; then
    err "Произошла ошибка при применении настроек sysctl."
fi

ok "Настройки безопасности ядра успешно применены."

exit 0
